apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# --> DANGER: Workspaces (Notebooks v2) is still pre-GA <--
#
# !!! DO NOT DEPLOY THIS TO A PRODUCTION CLUSTER !!!
#
# See this for the current status: https://www.kubeflow.org/docs/components/notebooks/notebooks-v2-pre-ga-banner
resources:
- ../../upstream/backend/overlays/istio
- ../../upstream/controller/overlays/istio
- ../../upstream/frontend/overlays/istio
- workspaces-base-edit-clusterrole.yaml

patches:
- patch: |-
    - op: replace
      path: /rules
      value: []
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kubeflow-workspaces-edit

# Can be dropped with the next release:
# https://github.com/kubeflow/notebooks/pull/1032
images:
- name: ghcr.io/kubeflow/notebooks/workspaces-backend
  newTag: 2.0.0-alpha.1
- name: ghcr.io/kubeflow/notebooks/workspaces-controller
  newTag: 2.0.0-alpha.1
- name: ghcr.io/kubeflow/notebooks/workspaces-frontend
  newTag: 2.0.0-alpha.1
