apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-workspaces-base-edit
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-workspaces-edit: "true"
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - workspaces
  - workspaces/status
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
