{{- if eq (include "kubeflow-namespaces.shouldRenderNamespace" (dict "root" . "name" .Values.global.namespace)) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    control-plane: kubeflow
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
  name: {{ .Values.global.namespace }}
{{- end }}
---
{{- if eq (include "kubeflow-namespaces.shouldRenderNamespace" (dict "root" . "name" .Values.global.systemNamespace)) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    control-plane: kubeflow
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
  name: {{ .Values.global.systemNamespace }}
{{- end }}
---
{{- if eq (include "kubeflow-namespaces.shouldRenderNamespace" (dict "root" . "name" "cert-manager")) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    pod-security.kubernetes.io/enforce: restricted
  name: cert-manager
{{- end }}
---
{{- if eq (include "kubeflow-namespaces.shouldRenderNamespace" (dict "root" . "name" "istio-system")) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    istio-injection: disabled
    istio-operator-managed: Reconcile
    pod-security.kubernetes.io/enforce: restricted
  name: istio-system
{{- end }}
---
{{- if eq (include "kubeflow-namespaces.shouldRenderNamespace" (dict "root" . "name" "oauth2-proxy")) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    pod-security.kubernetes.io/enforce: restricted
  name: oauth2-proxy
{{- end }}
---
{{- if eq (include "kubeflow-namespaces.shouldRenderNamespace" (dict "root" . "name" "auth")) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    pod-security.kubernetes.io/enforce: restricted
  name: auth
{{- end }}

# TODO: Add knative-serving and knative-eventing namespaces when the
# knative wrapper chart PR is opened.
