apiVersion: v2

name: kserve-models-web-application

description: A Helm chart for the KServe Models Web Application

version: 0.1.2

appVersion: "v1.0.1"

home: https://github.com/kserve/kserve

annotations:
  category: Machine Learning
  licenses: Apache-2.0
