apiVersion: v1
kind: ConfigMap
metadata:
  name: restricted-pytorch-init-container
data:
  initContainer.yaml: |
    - name: init-pytorch
      image: "{{.InitContainerImage}}"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 20Mi
        requests:
          cpu: 50m
          memory: 10Mi
      command: ['sh', '-c', 'err=1;for i in $(seq {{.MaxTries}}); do if nslookup {{.MasterAddr}}; then err=0 && break; fi;echo waiting for master; sleep 2; done; exit $err']
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
