{{- if .Values.m2m.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: m2m-token-issuer
  namespace: {{ include "oauth2-proxy.istioNamespace" . }}
spec:
  jwtRules:
{{ include "oauth2-proxy.m2mJwtRule" (dict "issuer" .Values.m2m.issuer "jwksUri" .Values.m2m.jwksUri) | nindent 2 }}
{{- range .Values.m2m.additionalJwtRules }}
{{ include "oauth2-proxy.m2mJwtRule" (dict "issuer" .issuer "jwksUri" .jwksUri) | nindent 2 }}
{{- end }}
  selector:
    matchLabels:
      app: istio-ingressgateway
{{- end }}
