apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../upstream/installs/katib-with-kubeflow
configMapGenerator:
- behavior: merge
  files:
  - katib-config.yaml
  name: katib-config
  options:
    disableNameSuffixHash: true
