apiVersion: v1
kind: Secret
metadata:
  name: model-catalog-postgres
  namespace: kubeflow
type: Opaque
data:
  POSTGRES_USER: {{ required "generated database username is missing" (.Files.Get "manifests/documents/database-username.txt" | trim) | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: model-catalog-hf-api-key
  namespace: kubeflow
type: Opaque
data:
  HF_API_KEY: {{ .Values.huggingFaceApiKey | b64enc | quote }}
