apiVersion: v2

name: kubeflow-namespaces

description: A Helm chart for Kubeflow platform namespaces and namespace network policies

version: 0.1.1

keywords:
- kubeflow
- namespaces
- network-policy

home: https://github.com/kubeflow/community-distribution

sources:
- https://github.com/kubeflow/community-distribution/tree/master/common/kubeflow-namespace

annotations:
  category: Machine Learning
  licenses: Apache-2.0
