apiVersion: v1
kind: Secret
metadata:
  name: model-registry-db-secrets
  namespace: kubeflow-user-example-com
type: Opaque
data:
  POSTGRES_USER: {{ required "generated database username is missing" (.Files.Get "manifests/documents/database-username.txt" | trim) | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
