#!/usr/bin/env python3
"""Shared engine that turns a Kustomize build into Helm chart payloads.

A component supplies a GeneratorConfiguration describing where to build from,
where to write, which resources its chart renders by hand, and which embedded
documents to extract. Everything else - Kubernetes identity validation,
duplicate detection, custom resource definition retention, deterministic
rendering and atomic replacement - is component independent and lives here.

A resource that reaches a payload keeps the content Kustomize rendered, with two
controlled transforms: every custom resource definition receives the
helm.sh/resource-policy: keep annotation, and an aggregated ClusterRole loses its
empty rules field, which the aggregation controller owns.

Helm loads the generated payloads with .Files.Get, which does not send content
through the template renderer, so Go template delimiters that upstream manifests
legitimately contain survive verbatim.
"""

import argparse
import copy
import io
import os
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
import uuid

from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path

from ruamel.yaml import YAML

CRD_KIND = "CustomResourceDefinition"
CRD_RETENTION_ANNOTATION = "helm.sh/resource-policy"
CLUSTER_ROLE_API_GROUP = "rbac.authorization.k8s.io"
CLUSTER_ROLE_KIND = "ClusterRole"
KUSTOMIZE_HASH_PATTERN = r"[a-z0-9]{10}"
DOCUMENTS_DIRECTORY = "documents"
DEFAULT_DIRECTORY_MODE = 0o755


@dataclass(frozen=True)
class GeneratorConfiguration:
    """Everything that differs between components."""

    component_name: str
    kustomize_path: Path
    output_path: Path
    generator_script: str
    synchronize_script: str
    # None declares that this component has no definitions. Unexpected CRDs
    # then fail generation instead of acquiring an unreviewed lifecycle.
    crds_payload_filename: str | None = "platform-crds.yaml"
    # When set, every custom resource definition is written to its own file,
    # <directory>/<definition name>.yaml, instead of crds_payload_filename.
    # Helm refuses to load any chart file above 5 MiB, and one component's
    # definitions together can exceed that.
    crds_payload_directory: str = ""
    resources_payload_filename: str | None = "platform-resources.yaml"
    # (API group, kind), for releases owning disjoint parts of one baseline.
    included_resource_kinds: tuple = ()
    excluded_resource_kinds: tuple = ()
    # (kind, name or name prefix, name_is_prefix)
    hand_written_resources: tuple = ()
    # (kind, name or name prefix, name_is_prefix, data key, output filename)
    extracted_documents: tuple = ()
    # (kind, name): rendered by Kustomize but owned by another Helm release, so
    # left out of every payload and rendered by no template either.
    excluded_resources: tuple = ()

    def generated_header(self):
        return (
            f"# Code generated by {self.generator_script}. DO NOT EDIT.\n"
            f"# Source: kustomize build {self.kustomize_path}\n"
            f"# Regenerate with: KUBEFLOW_SYNCHRONIZE_NO_COMMIT=true "
            f"./{self.synchronize_script}\n"
        )


def resource_identity(resource):
    if not isinstance(resource, Mapping):
        raise ValueError("resource identity requires a YAML mapping")

    api_version = resource.get("apiVersion")
    kind = resource.get("kind")
    metadata = resource.get("metadata")
    if not isinstance(api_version, str) or not api_version:
        raise ValueError("resource identity is missing apiVersion")
    if not isinstance(kind, str) or not kind:
        raise ValueError("resource identity is missing kind")
    if not isinstance(metadata, Mapping):
        raise ValueError("resource identity is missing metadata")

    name = metadata.get("name")
    namespace = metadata.get("namespace", "")
    if not isinstance(name, str) or not name:
        raise ValueError("resource identity is missing metadata.name")
    if not isinstance(namespace, str):
        raise ValueError("resource identity has a non-string metadata.namespace")

    return api_version, kind, namespace, name


def kubernetes_object_identity(resource):
    api_version, kind, namespace, name = resource_identity(resource)
    api_group = api_version.split("/", maxsplit=1)[0] if "/" in api_version else ""
    return api_group, kind, namespace, name


def matches_selector(resource, kind, name, name_is_prefix):
    _, resource_kind, _, resource_name = resource_identity(resource)
    if resource_kind != kind:
        return False
    if not name_is_prefix:
        return resource_name == name
    return (
        re.fullmatch(re.escape(name) + KUSTOMIZE_HASH_PATTERN, resource_name)
        is not None
    )


def parse_resources(rendered_yaml, *, preserve_quotes=False):
    yaml = YAML()
    yaml.preserve_quotes = preserve_quotes
    yaml.allow_duplicate_keys = False
    resources = []
    for document_number, resource in enumerate(yaml.load_all(rendered_yaml), start=1):
        if resource is None:
            continue
        if not isinstance(resource, Mapping):
            raise ValueError(
                f"YAML document {document_number} is not a Kubernetes resource mapping"
            )
        resources.append(resource)
    if not resources:
        raise ValueError("Kustomize rendered no Kubernetes resources")
    return resources


def add_crd_retention(resource):
    retained_resource = copy.deepcopy(resource)
    metadata = retained_resource["metadata"]
    annotations = metadata.get("annotations")
    if annotations is None:
        annotations = {}
        metadata["annotations"] = annotations
    if not isinstance(annotations, Mapping):
        raise ValueError(
            f"CRD {resource_identity(resource)} has non-mapping metadata.annotations"
        )
    annotations[CRD_RETENTION_ANNOTATION] = "keep"
    return retained_resource


def omit_aggregated_cluster_role_rules(resource):
    """Omit the empty rules field of an aggregated ClusterRole.

    The aggregation controller owns the rules of a ClusterRole that carries an
    aggregationRule. A manifest that sets the field, even to an empty list,
    claims it under server-side apply, so every later helm upgrade fails with a
    conflict against clusterrole-aggregation-controller. Kubernetes documents
    that such a manifest omits the field. Every other resource is returned as it
    is; the input is never changed.
    """
    api_group, kind, _, name = kubernetes_object_identity(resource)
    if api_group != CLUSTER_ROLE_API_GROUP or kind != CLUSTER_ROLE_KIND:
        return resource
    aggregation_rule = resource.get("aggregationRule")
    if not isinstance(aggregation_rule, Mapping):
        return resource
    selectors = aggregation_rule.get("clusterRoleSelectors")
    if not isinstance(selectors, list) or not selectors:
        return resource
    if "rules" not in resource:
        return resource
    rules = resource["rules"]
    if rules is not None and not isinstance(rules, list):
        raise ValueError(f"aggregated ClusterRole {name} rules must be null or a list")
    if rules:
        raise ValueError(
            f"aggregated ClusterRole {name} has nonempty rules; hand-authored "
            "rules on an aggregated ClusterRole are overwritten by the "
            "aggregation controller, so they belong in a ClusterRole that the "
            "aggregationRule selects"
        )
    aggregated_role = copy.deepcopy(resource)
    del aggregated_role["rules"]
    return aggregated_role


def omit_aggregated_cluster_role_rules_from_yaml(rendered_yaml):
    """Apply the same ownership repair to standalone synchronization streams.

    Leave unaffected streams byte-identical. Preserve comments and quoted values
    when a stream needs the repair; validate the entire input before emitting it.
    """
    resources = parse_resources(rendered_yaml, preserve_quotes=True)
    repaired_resources = [
        omit_aggregated_cluster_role_rules(resource) for resource in resources
    ]
    if all(
        original is repaired
        for original, repaired in zip(resources, repaired_resources)
    ):
        return rendered_yaml
    yaml = YAML()
    yaml.width = 4096
    output = io.StringIO()
    yaml.dump_all(repaired_resources, output)
    return output.getvalue()


def render_payload(resources, header):
    yaml = YAML()
    yaml.default_flow_style = False
    yaml.explicit_start = True
    yaml.width = 4096
    stream = io.StringIO()
    yaml.dump_all(resources, stream)
    return header + stream.getvalue()


def extract_documents(resource, configuration):
    """Return the embedded documents this resource contributes."""
    documents = {}
    for (
        kind,
        name,
        name_is_prefix,
        data_key,
        filename,
    ) in configuration.extracted_documents:
        if not matches_selector(resource, kind, name, name_is_prefix):
            continue
        data = resource.get("data")
        if not isinstance(data, Mapping) or data_key not in data:
            raise ValueError(
                f"resource {resource_identity(resource)} is missing "
                f"data key {data_key!r} required for {filename}"
            )
        value = data[data_key]
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"resource {resource_identity(resource)} has an empty "
                f"data key {data_key!r} required for {filename}"
            )
        documents[f"{DOCUMENTS_DIRECTORY}/{filename}"] = value.rstrip("\n") + "\n"
    return documents


def generate_payload_contents(resources, configuration):
    crd_resources = []
    payload_resources = []
    documents = {}
    object_identities = set()
    matched_selectors = {}
    matched_exclusions = set()

    for resource in resources:
        identity = resource_identity(resource)
        object_identity = kubernetes_object_identity(resource)
        if object_identity in object_identities:
            raise ValueError(f"duplicate resource identity: {identity}")
        object_identities.add(object_identity)

        exclusion = (identity[1], identity[3])
        if exclusion in configuration.excluded_resources:
            matched_exclusions.add(exclusion)
            continue

        resource_kind = object_identity[:2]
        if (
            configuration.included_resource_kinds
            and resource_kind not in configuration.included_resource_kinds
        ) or resource_kind in configuration.excluded_resource_kinds:
            continue

        hand_written_selector = next(
            (
                selector
                for selector in configuration.hand_written_resources
                if matches_selector(resource, *selector)
            ),
            None,
        )
        if hand_written_selector is not None:
            if hand_written_selector in matched_selectors:
                raise ValueError(
                    f"resource {identity} matches hand-written selector "
                    f"{hand_written_selector} already matched by "
                    f"{matched_selectors[hand_written_selector]}"
                )
            matched_selectors[hand_written_selector] = identity
            documents.update(extract_documents(resource, configuration))
            continue

        resource = omit_aggregated_cluster_role_rules(resource)
        if resource["kind"] == CRD_KIND:
            crd_resources.append(add_crd_retention(resource))
        else:
            payload_resources.append(copy.deepcopy(resource))

    unmatched_selectors = [
        selector
        for selector in configuration.hand_written_resources
        if selector not in matched_selectors
    ]
    if unmatched_selectors:
        raise ValueError(
            "hand-written resources are no longer rendered by Kustomize; "
            "their templates are orphaned: "
            + ", ".join(f"{kind}/{name}" for kind, name, _ in unmatched_selectors)
        )

    stale_exclusions = [
        exclusion
        for exclusion in configuration.excluded_resources
        if exclusion not in matched_exclusions
    ]
    if stale_exclusions:
        raise ValueError(
            "excluded resources are no longer rendered by Kustomize; "
            "the exclusions are stale: "
            + ", ".join(f"{kind}/{name}" for kind, name in stale_exclusions)
        )

    missing_documents = [
        f"{DOCUMENTS_DIRECTORY}/{filename}"
        for *_, filename in configuration.extracted_documents
        if f"{DOCUMENTS_DIRECTORY}/{filename}" not in documents
    ]
    if missing_documents:
        raise ValueError(
            "required embedded documents were not extracted: "
            + ", ".join(missing_documents)
        )

    if configuration.crds_payload_filename is None:
        if configuration.crds_payload_directory:
            raise ValueError(
                "component declares no custom resource definitions but configures their directory"
            )
        if crd_resources:
            raise ValueError(
                "component declares no custom resource definitions but Kustomize renders them"
            )
        crd_payloads = []
    elif configuration.crds_payload_directory:
        crds_payload_name = configuration.crds_payload_directory + "/"
        crd_payloads = [
            (
                f"{configuration.crds_payload_directory}/"
                f"{resource_identity(resource)[3]}.yaml",
                [resource],
            )
            for resource in crd_resources
        ]
    else:
        crds_payload_name = configuration.crds_payload_filename
        crd_payloads = []
        if configuration.crds_payload_filename is not None:
            crd_payloads = [(configuration.crds_payload_filename, crd_resources)]
        elif crd_resources:
            raise ValueError("selected definitions have no payload destination")
    payloads = list(crd_payloads)
    if configuration.resources_payload_filename is not None:
        payloads.append((configuration.resources_payload_filename, payload_resources))
    elif payload_resources:
        raise ValueError("selected resources have no payload destination")
    empty_payloads = [filename for filename, entries in payloads if not entries]
    # The single-file layout records its empty definition payload through the
    # loop above; the per-definition layout has no file to record, so name the
    # directory instead.
    if configuration.crds_payload_directory and not crd_resources:
        empty_payloads.insert(0, crds_payload_name)
    if not payloads and not empty_payloads:
        raise ValueError("required generated payloads are empty")
    if empty_payloads:
        raise ValueError(
            "required generated payloads are empty: " + ", ".join(empty_payloads)
        )

    header = configuration.generated_header()
    contents = {
        filename: render_payload(entries, header) for filename, entries in payloads
    }
    contents.update(documents)
    return contents


def write_payloads_atomically(output_directory, payloads):
    """Replace the output directory in one step, preserving its mode.

    tempfile.mkdtemp creates the staging directory as 0700. Moving it into place
    without restoring the mode would leave the generated payloads unreadable to
    any other user or containerized packaging step, and Git does not record
    directory modes, so a fresh checkout would hide the problem.
    """
    output_directory = Path(output_directory)
    output_directory.parent.mkdir(parents=True, exist_ok=True)
    if output_directory.exists():
        directory_mode = stat.S_IMODE(output_directory.stat().st_mode)
    else:
        directory_mode = DEFAULT_DIRECTORY_MODE
    staging_directory = Path(
        tempfile.mkdtemp(
            prefix=f".{output_directory.name}.new-",
            dir=output_directory.parent,
        )
    )
    backup_directory = output_directory.parent / (
        f".{output_directory.name}.old-{uuid.uuid4().hex}"
    )
    previous_directory_moved = False

    try:
        for filename, contents in payloads.items():
            relative_path = Path(filename)
            if relative_path.is_absolute() or ".." in relative_path.parts:
                raise ValueError(f"payload filename must be relative: {filename}")
            if len(relative_path.parts) > 2:
                raise ValueError(
                    f"payload filename must not nest more than one directory: "
                    f"{filename}"
                )
            if not contents.strip():
                raise ValueError(f"generated payload is empty: {filename}")
            destination = staging_directory / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(contents, encoding="utf-8", newline="\n")

        for directory in [staging_directory, *staging_directory.iterdir()]:
            if directory.is_dir():
                os.chmod(directory, directory_mode)

        if output_directory.exists():
            os.replace(output_directory, backup_directory)
            previous_directory_moved = True

        try:
            os.replace(staging_directory, output_directory)
        except Exception:
            if previous_directory_moved:
                os.replace(backup_directory, output_directory)
                previous_directory_moved = False
            raise

        if previous_directory_moved:
            shutil.rmtree(backup_directory)
            previous_directory_moved = False
    finally:
        if staging_directory.exists():
            shutil.rmtree(staging_directory)
        if previous_directory_moved and backup_directory.exists():
            if not output_directory.exists():
                os.replace(backup_directory, output_directory)


def render_manifests(repository_root, configuration):
    """Build the Kustomize inputs and return (resource count, {filename: text}).

    Nothing is written; generate_manifests and check_manifests share this step
    so the freshness check sees exactly the bytes generation would write.
    """
    repository_root = Path(repository_root).resolve()
    result = subprocess.run(
        ["kustomize", "build", str(configuration.kustomize_path)],
        cwd=repository_root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"{configuration.component_name} Kustomize build failed:\n"
            + result.stderr.rstrip()
        )

    resources = parse_resources(result.stdout)
    return len(resources), generate_payload_contents(resources, configuration)


def generate_manifests(repository_root, configuration):
    repository_root = Path(repository_root).resolve()
    resource_count, payloads = render_manifests(repository_root, configuration)
    write_payloads_atomically(repository_root / configuration.output_path, payloads)
    return resource_count, tuple(payloads)


def check_manifests(repository_root, configuration):
    """Compare what generation would write with what the output directory holds.

    Returns a sorted list of (status, relative path) where status is "stale"
    (bytes differ), "missing" (would be generated, absent on disk) or "extra"
    (present on disk, would not be generated; generation deletes such a file).
    An empty list means the committed payloads are fresh. Bytes are compared,
    not decoded text, so a line-ending change is a difference.
    """
    repository_root = Path(repository_root).resolve()
    output_directory = repository_root / configuration.output_path
    _, payloads = render_manifests(repository_root, configuration)
    expected = {
        Path(filename): contents.encode("utf-8")
        for filename, contents in payloads.items()
    }

    actual = set()
    if output_directory.is_dir():
        actual = {
            path.relative_to(output_directory)
            for path in output_directory.rglob("*")
            if not path.is_dir()
        }

    differences = []
    for relative_path, contents in expected.items():
        if relative_path not in actual:
            differences.append(("missing", relative_path.as_posix()))
        elif (output_directory / relative_path).read_bytes() != contents:
            differences.append(("stale", relative_path.as_posix()))
    for relative_path in actual - set(expected):
        differences.append(("extra", relative_path.as_posix()))
    return sorted(differences, key=lambda difference: difference[1])


def command_line(configuration, description, default_repository_root, argv=None):
    """Shared entry point of every generator script: generate, or --check.

    Without --check the payloads are regenerated in place. With --check nothing
    is written; every stale, missing or extra file is listed with the local
    command that repairs it, and the exit status is 1. Exit status is the
    contract; the messages are for people.
    """
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=None,
        help="Path to the kubeflow/community-distribution repository.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report payloads that regeneration would change, without writing.",
    )
    arguments = parser.parse_args(argv)
    repository_root = arguments.repository_root or default_repository_root
    # The repair is the generator itself, run from the repository root. The
    # synchronization script is a different operation: it imports upstream.
    # The repair is quoted for a shell and names the resolved root, because it
    # is meant to be run from the repository root, where a relative path typed
    # elsewhere would point at a different tree.
    repair = ["python3", configuration.generator_script]
    if arguments.repository_root is not None:
        repair += ["--repository-root", str(Path(arguments.repository_root).resolve())]
    repair = shlex.join(repair)

    try:
        if arguments.check:
            differences = check_manifests(repository_root, configuration)
        else:
            resource_count, payload_filenames = generate_manifests(
                repository_root, configuration
            )
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if not arguments.check:
        print(
            f"Generated {resource_count} {configuration.component_name} resources "
            f"across {len(payload_filenames)} files."
        )
        return 0

    if differences:
        print(
            f"ERROR: {configuration.component_name} payloads in "
            f"{configuration.output_path} are not what "
            f"{configuration.generator_script} generates:",
            file=sys.stderr,
        )
        for status, filename in differences:
            print(f"  {status:8} {filename}", file=sys.stderr)
        print(f"Regenerate with: {repair}", file=sys.stderr)
        return 1
    print(
        f"{configuration.component_name} payloads in {configuration.output_path} "
        "are fresh."
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Repair generated Helm YAML from stdin."
    )
    parser.add_argument(
        "--omit-aggregated-cluster-role-rules",
        action="store_true",
        required=True,
        help="Omit controller-owned empty rules from aggregated ClusterRoles.",
    )
    parser.parse_args()
    try:
        sys.stdout.write(omit_aggregated_cluster_role_rules_from_yaml(sys.stdin.read()))
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        sys.exit(1)
