#!/usr/bin/env bash
# This script helps to create a PR to update the unified Istio manifests
SCRIPT_DIRECTORY=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${SCRIPT_DIRECTORY}/library.sh"
setup_error_handling
COMPONENT_NAME="istio"
REPOSITORY_NAME="istio/istio"
COMMIT="1.31.0"
PREVIOUS_COMMIT="1.30.3"
SOURCE_DIRECTORY=${SOURCE_DIRECTORY:=/tmp/kubeflow-${COMPONENT_NAME}}
BRANCH_NAME=${BRANCH_NAME:=synchronize-${COMPONENT_NAME}-manifests-${COMMIT?}}
MANIFESTS_DIRECTORY=$(dirname $SCRIPT_DIRECTORY)
ISTIO_DIRECTORY=$MANIFESTS_DIRECTORY/common/${COMPONENT_NAME}
HELM_MANIFESTS_DIRECTORY="$ISTIO_DIRECTORY/helm/manifests"
create_branch "$BRANCH_NAME"
mkdir -p "$SOURCE_DIRECTORY"
mkdir -p "$HELM_MANIFESTS_DIRECTORY"
cd "$SOURCE_DIRECTORY"
if [ ! -d "istio-${COMMIT}" ]; then
    wget "https://github.com/${REPOSITORY_NAME}/releases/download/${COMMIT}/istio-${COMMIT}-linux-amd64.tar.gz"
    tar xvfz istio-${COMMIT}-linux-amd64.tar.gz
fi
ISTIOCTL="${SOURCE_DIRECTORY}/istio-${COMMIT}/bin/istioctl"
cd "$ISTIO_DIRECTORY"
sed -i "s/tag: .*/tag: $COMMIT/" "$ISTIO_DIRECTORY/profile.yaml"
$ISTIOCTL manifest generate -f profile.yaml -f profile-overlay.yaml \
  --set components.cni.enabled=true \
  --set components.cni.namespace=kube-system > dump.yaml
./split-istio-packages -f dump.yaml
sed -i -e 's/[[:space:]]\+$//' -e '${/^$/d;}' \
  crd.yaml install.yaml cluster-local-gateway.yaml
mv $ISTIO_DIRECTORY/crd.yaml $ISTIO_DIRECTORY/istio-crds/base/
mv $ISTIO_DIRECTORY/install.yaml $ISTIO_DIRECTORY/istio-install/base/
mv $ISTIO_DIRECTORY/cluster-local-gateway.yaml $ISTIO_DIRECTORY/cluster-local-gateway/base/
rm dump.yaml
$ISTIOCTL manifest generate -f profile.yaml -f profile-overlay.yaml \
  --set components.cni.enabled=true \
  --set components.ztunnel.enabled=true > dump-ztunnel.yaml
./split-istio-packages -f dump-ztunnel.yaml
sed -i -e 's/[[:space:]]\+$//' -e '${/^$/d;}' \
  crd.yaml install.yaml cluster-local-gateway.yaml ztunnel.yaml
mv $ISTIO_DIRECTORY/ztunnel.yaml $ISTIO_DIRECTORY/istio-install/components/ambient-mode/
rm dump-ztunnel.yaml crd.yaml install.yaml cluster-local-gateway.yaml
sed -i "s/\"tag\": \".*\"/\"tag\": \"$COMMIT\"/" "$ISTIO_DIRECTORY/istio-install/base/patches/istio-sidecar-injector-patch.yaml"
# Normalize all remaining Istio version references from PREVIOUS_COMMIT to COMMIT.
# This catches any version strings that istioctl generates using the previous release
# (e.g. image tags, helm chart labels). Update PREVIOUS_COMMIT when needed.
find "$ISTIO_DIRECTORY" -name "*.yaml" \
  ! -path "$ISTIO_DIRECTORY/helm/Chart.yaml" -exec sed -i \
  -e "s/${PREVIOUS_COMMIT}/$COMMIT/g" {} +
update_helm_chart_application_version \
  "$ISTIO_DIRECTORY/helm/Chart.yaml" "$COMMIT"

normalize_generated_yaml() {
  sed \
    -e 's/[[:space:]]\+$//' \
    -e '${/^$/d;}'
}

render_helm_manifest_payload() {
  local source_path=$1

  {
    printf "# Generated by: kustomize build %s\n" "${source_path#"$MANIFESTS_DIRECTORY/"}"
    printf "# Refresh with scripts/synchronize-istio-manifests.sh for Istio %s.\n" "$COMMIT"
    kustomize build "$source_path"
  } | normalize_generated_yaml
}

render_helm_manifest() {
  local source_path=$1
  local output_file=$2

  write_generated_file_atomically \
    "$output_file" render_helm_manifest_payload "$source_path"
}

render_network_policies_manifest() {
  {
    printf "# Generated by: kustomize build common/istio/istio-namespace/base | sed '1,/^---$/d'\n"
    printf "# Refresh with scripts/synchronize-istio-manifests.sh for Istio %s.\n" "$COMMIT"
    kustomize build "$ISTIO_DIRECTORY/istio-namespace/base" | sed '1,/^---$/d'
  } | normalize_generated_yaml
}

render_helm_manifest "$ISTIO_DIRECTORY/istio-crds/base" \
  "$HELM_MANIFESTS_DIRECTORY/crds.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/istio-install/base" \
  "$HELM_MANIFESTS_DIRECTORY/install-base.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/istio-install/overlays/oauth2-proxy" \
  "$HELM_MANIFESTS_DIRECTORY/install-oauth2-proxy.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/istio-install/overlays/gke" \
  "$HELM_MANIFESTS_DIRECTORY/install-gke.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/cluster-local-gateway/base" \
  "$HELM_MANIFESTS_DIRECTORY/cluster-local-gateway.yaml"
render_helm_manifest "$ISTIO_DIRECTORY/kubeflow-istio-resources/base" \
  "$HELM_MANIFESTS_DIRECTORY/kubeflow-istio-resources.yaml"
write_generated_file_atomically \
  "$HELM_MANIFESTS_DIRECTORY/networkpolicies.yaml" \
  render_network_policies_manifest
SOURCE_TEXT="\[.*\](https://github.com/${REPOSITORY_NAME}/releases/tag/.*)"
DESTINATION_TEXT="\[$COMMIT\](https://github.com/${REPOSITORY_NAME}/releases/tag/$COMMIT)"
update_readme "$MANIFESTS_DIRECTORY" "$SOURCE_TEXT" "$DESTINATION_TEXT"
commit_changes "$MANIFESTS_DIRECTORY" "Update ${REPOSITORY_NAME} manifests from ${COMMIT}" \
  "README.md" \
  "scripts/synchronize-istio-manifests.sh" \
  "common/${COMPONENT_NAME}"
echo "Synchronization completed successfully."
