{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
{{- with .Values.namespace.labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ include "dex.namespace" . }}
{{- end }}
