apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspaces-frontend
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
