global:
  namespace: kserve

kubeflow:
  enabled: true

istio:
  virtualService:
    enabled: true
  authorizationPolicy:
    enabled: true

networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - istio-system
